# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeGpu < Formula
  desc "Inspect GPU allocation across a Kubernetes cluster"
  homepage "https://github.com/deBilla/kube-gpu"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.1/kube-gpu_darwin_amd64.tar.gz"
      sha256 "82813eadd951b9b722a77983764b86d4dbd9f9c120810357aa031ab24473451a"

      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.1/kube-gpu_darwin_arm64.tar.gz"
      sha256 "ccae7668368d18f3fdcc2d05e08e68e5ea9bae124d94474d7a3d00e7018c8be6"

      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.1/kube-gpu_linux_amd64.tar.gz"
      sha256 "7660d6156d1a8c05f55428765af7b0165f9caecdb5509b9fb839b25e96f67434"
      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.1/kube-gpu_linux_arm64.tar.gz"
      sha256 "75174e2b22bfcf95d8fda564f710b17176d1d6420db82f1bff632cc781f61cff"
      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
  end
end
