# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeGpu < Formula
  desc "Inspect GPU allocation across a Kubernetes cluster"
  homepage "https://github.com/deBilla/kube-gpu"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_darwin_amd64.tar.gz"
      sha256 "a8fe170a67b2bf132c3e457ca0119ea88bd7cd1634db49a0cc355c26aa023ee6"

      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_darwin_arm64.tar.gz"
      sha256 "60c3f92b5a49bcf2b4f1329af656649c24ea9eeaa5177ba092129eb926bda3e7"

      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_linux_amd64.tar.gz"
      sha256 "de6cd19f8aed22cb94b9c9d60bf47a39b4d7e32dc303732faa18569c68293f0b"
      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_linux_arm64.tar.gz"
      sha256 "e81f496ba4f387cbbbac244f19e19e60fcb121ca5c3ba7bd72914919938e3846"
      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
  end
end
