# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeGpu < Formula
  desc "Inspect GPU allocation across a Kubernetes cluster"
  homepage "https://github.com/deBilla/kube-gpu"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_darwin_amd64.tar.gz"
      sha256 "1490d9e04d6f90df3eb281a15ab60d42c4cfad777a8a0f3a8dc0e095f3568c93"

      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_darwin_arm64.tar.gz"
      sha256 "cb817d12b4e23458ca2aa47a6d22b50a18b5ca95a123d7a9d8962850c69a6ac0"

      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_linux_amd64.tar.gz"
      sha256 "5ef5c9720649961c7c6521ab619d785d801d1151c16df9f66a69d2856882309c"
      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deBilla/kube-gpu/releases/download/v0.1.0/kube-gpu_linux_arm64.tar.gz"
      sha256 "0ac053e4893cbd69f46a4e44f96c443e5040cbde627c5ec37582c784061430f6"
      define_method(:install) do
        bin.install "kube-gpu"
      end
    end
  end
end
